apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-deployment
  labels:
    app: camel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camel
  template:
    metadata:
      labels:
        app: camel
    spec:
      serviceAccountName: camel-leader
      containers:
      - name: camel
        image: localhost:5000/camel-k8s:latest
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace