apiVersion: v1
kind: ServiceAccount
metadata:
  name: camel-leader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: camel-leader
rules:
  - apiGroups:
      - ""
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camel-leader
subjects:
  - kind: ServiceAccount
    name: camel-leader
roleRef:
  kind: Role
  name: camel-leader
  apiGroup: rbac.authorization.k8s.io